# Generated by Django 5.0 on 2023-12-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_logged', models.DateField(auto_now_add=True)),
                ('date_due', models.DateField()),
                ('expense_name', models.CharField(max_length=100)),
                ('payer', models.CharField(max_length=50)),
            ],
        ),
    ]
